"""empty message

Revision ID: 0a7bfd4d9d07
Revises: 1a4646aec2ed
Create Date: 2019-08-28 21:46:30.404703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7bfd4d9d07'
down_revision = '1a4646aec2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('walk_miles', sa.Float(), nullable=True),
    sa.Column('run_miles', sa.Float(), nullable=True),
    sa.Column('total_miles', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('shoe', sa.String(length=75), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_shoe'), 'activity', ['shoe'], unique=False)
    op.create_index(op.f('ix_activity_user_id'), 'activity', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_user_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_shoe'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
